#!/bin/bash

git mv hello_world.py menu/
git mv todo.py menu/
git mv wizard.py menu/
git mv issue_tracker.py menu/
git mv dashboard.py menu/
git mv tall_info.py menu/
git mv article.py menu/
git mv wide_info.py menu/
git mv wide_plot.py menu/
git mv post.py menu/
git mv preview.py menu/
git mv stat_wide_pie.py menu/
git mv tall_article_preview.py menu/
git mv wide_article_preview.py menu/
git mv profile.py menu/
git mv stat_small.py menu/
git mv stat_large.py menu/
git mv stat_wide_gauge.py menu/
git mv stat_tall_gauge.py menu/
git mv stat_wide_bar.py menu/
git mv stat_wide_pie.py menu/
git mv stat_large_bar.py menu/
git mv stat_small_series_area.py menu/
git mv stat_small_series_interval.py menu/
git mv stat_wide_series_area.py menu/
git mv stat_wide_series_interval.py menu/
git mv stat_tall_series_area.py menu/
git mv stat_tall_series_interval.py menu/
git mv stat_table.py menu/
git mv tall_stats.py menu/
git mv layout.py menu/
git mv layout_size.py menu/
git mv layout_responsive.py menu/
git mv form.py menu/
git mv form_visibility.py menu/
git mv text.py menu/
git mv copyable_text.py menu/
git mv text_sizes.py menu/
git mv text_annotator.py menu/
git mv label.py menu/
git mv link.py menu/
git mv links.py menu/
git mv progress.py menu/
git mv progress_update.py menu/
git mv message_bar.py menu/
git mv textbox.py menu/
git mv textbox_trigger.py menu/
git mv button.py menu/
git mv buttons.py menu/
git mv checkbox.py menu/
git mv checklist.py menu/
git mv checklist_inline.py menu/
git mv picker.py menu/
git mv picker_selection.py menu/
git mv dropdown.py menu/
git mv choice_group.py menu/
git mv combobox.py menu/
git mv toggle.py menu/
git mv spinbox.py menu/
git mv spinbox_trigger.py menu/
git mv slider.py menu/
git mv range_slider.py menu/
git mv date_picker.py menu/
git mv date_picker_trigger.py menu/
git mv time_picker.py menu/
git mv color_picker.py menu/
git mv swatch_picker.py menu/
git mv persona.py menu/
git mv facepile.py menu/
git mv tabs.py menu/
git mv separator.py menu/
git mv file_upload.py menu/
git mv file_upload_compact.py menu/
git mv form_frame.py menu/
git mv form_frame_path.py menu/
git mv form_template.py menu/
git mv form_markup.py menu/
git mv stepper.py menu/
git mv table_markdown_pandas.py menu/
git mv table.py menu/
git mv table_sort.py menu/
git mv table_search.py menu/
git mv table_filter.py menu/
git mv table_filter_backend.py menu/
git mv table_download.py menu/
git mv table_groupby.py menu/
git mv table_groups.py menu/
git mv table_select.py menu/
git mv table_tags.py menu/
git mv table_pagination.py menu/
git mv table_pagination_pandas.py menu/
git mv table_pagination_h2o3.py menu/
git mv table_pagination_minimal.py menu/
git mv table_pagination_sort.py menu/
git mv table_pagination_filter.py menu/
git mv table_pagination_search.py menu/
git mv table_pagination_download.py menu/
git mv table_pagination_groups.py menu/
git mv table_menu.py menu/
git mv table_markdown.py menu/
git mv tags.py menu/
git mv image.py menu/
git mv image_annotator.py menu/
git mv file_stream.py menu/
git mv frame.py menu/
git mv frame_path.py menu/
git mv template.py menu/
git mv template_data.py menu/
git mv markdown.py menu/
git mv markdown_table.py menu/
git mv markdown_data.py menu/
git mv markdown_submit_text.py menu/
git mv markup.py menu/
git mv nav.py menu/
git mv toolbar.py menu/
git mv tab.py menu/
git mv tab_delete.py menu/
git mv breadcrumbs.py menu/
git mv header.py menu/
git mv footer.py menu/
git mv routing.py menu/
git mv routing_predicates.py menu/
git mv hash_routing.py menu/
git mv hash_routing_parameters.py menu/
git mv toolbar_routing.py menu/
git mv card_menu.py menu/
git mv menu.py menu/
git mv plot_theme.py menu/
git mv plot_point.py menu/
git mv plot_point_shapes.py menu/
git mv plot_point_sizes.py menu/
git mv plot_point_map.py menu/
git mv plot_point_groups.py menu/
git mv plot_point_annotation.py menu/
git mv plot_point_custom.py menu/
git mv plot_interval.py menu/
git mv plot_interval_transpose.py menu/
git mv plot_interval_groups.py menu/
git mv plot_interval_groups_transpose.py menu/
git mv plot_interval_labels.py menu/
git mv plot_interval_range.py menu/
git mv plot_interval_range_transpose.py menu/
git mv plot_interval_stacked.py menu/
git mv plot_interval_stacked_transpose.py menu/
git mv plot_interval_stacked_grouped.py menu/
git mv plot_interval_stacked_grouped_transpose.py menu/
git mv plot_interval_polar.py menu/
git mv plot_interval_polar_stacked.py menu/
git mv plot_interval_theta.py menu/
git mv plot_interval_theta_stacked.py menu/
git mv plot_interval_helix.py menu/
git mv plot_interval_annotation.py menu/
git mv plot_interval_annotation_transpose.py menu/
git mv plot_line.py menu/
git mv plot_line_groups.py menu/
git mv plot_line_smooth.py menu/
git mv plot_step.py menu/
git mv plot_step_after.py menu/
git mv plot_step_before.py menu/
git mv plot_line_labels.py menu/
git mv plot_line_labels_custom.py menu/
git mv plot_line_labels_stroked.py menu/
git mv plot_line_labels_no_overlap.py menu/
git mv plot_line_annotation.py menu/
git mv plot_path.py menu/
git mv plot_path_point.py menu/
git mv plot_path_smooth.py menu/
git mv plot_area.py menu/
git mv plot_area_groups.py menu/
git mv plot_area_negative.py menu/
git mv plot_area_range.py menu/
git mv plot_area_smooth.py menu/
git mv plot_area_stacked.py menu/
git mv plot_area_line.py menu/
git mv plot_area_line_smooth.py menu/
git mv plot_area_line_groups.py menu/
git mv plot_polygon.py menu/
git mv plot_histogram.py menu/
git mv plot_schema.py menu/
git mv plot_schema_transpose.py menu/
git mv plot_interaction_zoom.py menu/
git mv plot_interaction_brush.py menu/
git mv plot_interaction_drag_move.py menu/
git mv plot_axis_title.py menu/
git mv plot_form.py menu/
git mv plot_app.py menu/
git mv plot_events.py menu/
git mv plot_events_disabled.py menu/
git mv plot_events_routing.py menu/
git mv plot_pandas.py menu/
git mv plot_vega.py menu/
git mv plot_vegalite.py menu/
git mv plot_vegalite_update.py menu/
git mv plot_vegalite_form.py menu/
git mv plot_vegalite_flex.py menu/
git mv plot_altair.py menu/
git mv plot_bokeh.py menu/
git mv plot_bokeh_script.py menu/
git mv plot_bokeh_callbacks.py menu/
git mv plot_matplotlib.py menu/
git mv plot_plotly.py menu/
git mv plot_d3.py menu/
git mv pixel_art.py menu/
git mv upload.py menu/
git mv upload_async.py menu/
git mv upload_ui.py menu/
git mv upload_download.py menu/
git mv upload_frame.py menu/
git mv meta_inline_script.py menu/
git mv meta_inline_script_callback.py menu/
git mv meta_script.py menu/
git mv meta_script_callback.py menu/
git mv meta_stylesheet.py menu/
git mv meta_inline_stylesheet.py menu/
git mv meta_dialog.py menu/
git mv meta_dialog_closable.py menu/
git mv meta_side_panel.py menu/
git mv meta_side_panel_closable.py menu/
git mv meta_title.py menu/
git mv meta_icon.py menu/
git mv meta_notification.py menu/
git mv meta_notification_bar.py menu/
git mv meta_notification_bar_closable.py menu/
git mv meta_refresh.py menu/
git mv meta_redirect.py menu/
git mv meta_theme.py menu/
git mv theme_generator.py menu/
git mv meta_tracking.py menu/
git mv counter_global.py menu/
git mv counter_broadcast.py menu/
git mv counter_multicast.py menu/
git mv counter_unicast.py menu/
git mv background.py menu/
git mv background_executor.py menu/
git mv background_progress.py menu/
git mv site_async.py menu/
git mv http_client.py menu/
git mv checkpoint.py menu/
git mv graphics_primitives.py menu/
git mv graphics_spline.py menu/
git mv graphics_clock.py menu/
git mv graphics_path.py menu/
git mv graphics_turtle.py menu/
git mv graphics_hilbert.py menu/
git mv glider_gun.py menu/
git mv ml_h2o.py menu/
git mv ml_h2o_save.py menu/
git mv ml_h2o_categorical.py menu/
git mv ml_h2o_parameters.py menu/
git mv ml_h2o_algo.py menu/
git mv ml_h2o_shap.py menu/
git mv ml_dai.py menu/
git mv ml_dai_save.py menu/
git mv ml_dai_categorical.py menu/
git mv ml_dai_parameters.py menu/
git mv ml_dai_autodoc.py menu/
git mv ml_dai_instances.py menu/
